/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlAudio;
import Control.ControlCategoria;
import Control.ControlCuenta;
import Control.ControlImagen;
import Control.ControlVideo;
import Modelo.Categoria;
import Modelo.CuentaUsuario;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mateo
 */
public class Administrador extends javax.swing.JFrame {

    DefaultTableModel tablaCuentasImagenes;
    DefaultTableModel tablaCuentasVideos;
    DefaultTableModel tablaCuentasAudios;

    DefaultTableModel tablaContenidoComentarios;

    //**************************************************************************
    Cuenta GUIcuenta;

    DefaultListModel listaCategorias;

    String nombreCategoria;

    LinkedList<Categoria> categoriasRegistradas;
    LinkedList<String> cuentasImagenes;
    LinkedList<String> cuentasVideos;
    LinkedList<String> cuentasAudios;

    LinkedList<String> ContenidosComentarios;

    public Administrador() {
        initComponents();
        this.setLocationRelativeTo(this);
        listaCategorias = new DefaultListModel();
        ListaCategorias.setModel(listaCategorias);
        categoriasRegistradas = new LinkedList<>();
        cuentasImagenes = new LinkedList<>();
        cuentasVideos = new LinkedList<>();
        cuentasAudios = new LinkedList<>();
        ContenidosComentarios = new LinkedList<>();

        DesplegarCategorias();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCuentas = new javax.swing.JTable();
        Mostrar1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCuentaVideos = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        NombreC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        ListaCategorias = new javax.swing.JList<>();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Mostrar2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableCuentaAudios = new javax.swing.JTable();
        Mostrar3 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableContenidoComentarios = new javax.swing.JTable();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINISTRADOR REPOSITORIO MULTIMEDIA");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Datos cuentas con imágenes agregados al repositorio");

        jTableCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NombreUsuario", "Nombres", "Nombre Imagen", "Fecha subida", "Formato Imagen", "Resolución", "Categoría"
            }
        ));
        jScrollPane2.setViewportView(jTableCuentas);

        Mostrar1.setText("Mostrar ");
        Mostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Datos cuentas con videos agregados al repositorio");

        jTableCuentaVideos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NombreUsuario", "Nombres", "Nombre video", "Fecha subida", "Formato Video", "Duración", "Categoría"
            }
        ));
        jScrollPane4.setViewportView(jTableCuentaVideos);
        if (jTableCuentaVideos.getColumnModel().getColumnCount() > 0) {
            jTableCuentaVideos.getColumnModel().getColumn(0).setHeaderValue("Nombre contenido");
            jTableCuentaVideos.getColumnModel().getColumn(1).setHeaderValue("Fecha Subida");
            jTableCuentaVideos.getColumnModel().getColumn(5).setHeaderValue("Tamaño Audio");
            jTableCuentaVideos.getColumnModel().getColumn(6).setHeaderValue("Duración");
        }

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setText("Regresar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.setText("Salir");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Agregar categoría");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Nombre");

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("Máximo 20 caracteres");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Categorías registradas");

        jScrollPane5.setViewportView(ListaCategorias);

        jButton6.setText("Eliminar categoría");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton9.setText("Actualizar categoría");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(NombreC)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jLabel11))
                .addGap(25, 25, 25)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Mostrar2.setText("Mostrar ");
        Mostrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Datos cuentas con audios agregados al repositorio");

        jTableCuentaAudios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NombreUsuario", "Nombres", "Nombre Audio", "Fecha Subida", "Formato Audio", "Tamaño Audio", "Duración", "Categoría"
            }
        ));
        jScrollPane6.setViewportView(jTableCuentaAudios);
        if (jTableCuentaAudios.getColumnModel().getColumnCount() > 0) {
            jTableCuentaAudios.getColumnModel().getColumn(0).setHeaderValue("Nombre contenido");
            jTableCuentaAudios.getColumnModel().getColumn(1).setHeaderValue("Fecha Subida");
            jTableCuentaAudios.getColumnModel().getColumn(5).setHeaderValue("Tamaño Audio");
            jTableCuentaAudios.getColumnModel().getColumn(6).setHeaderValue("Duración");
            jTableCuentaAudios.getColumnModel().getColumn(7).setHeaderValue("Categoría");
        }

        Mostrar3.setText("Mostrar ");
        Mostrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar3ActionPerformed(evt);
            }
        });

        jTableContenidoComentarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Descripción comentario", "Fecha publicacion", "Nombre Usuario", "Nombre contenido", "Fecha subida"
            }
        ));
        jScrollPane7.setViewportView(jTableContenidoComentarios);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Datos contenidos multimedia vinculados con sus comentarios");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jButton1.setText("Ejecutar imágenes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ejecutar videos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ejecutar audios");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator9)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4)
                            .addComponent(jSeparator5)
                            .addComponent(jSeparator4)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(Mostrar1)
                                    .addComponent(jLabel7)
                                    .addComponent(Mostrar2)
                                    .addComponent(jLabel8)
                                    .addComponent(Mostrar3))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Mostrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Mostrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Mostrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1275, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Mostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar1ActionPerformed

        ControlCuenta Ccuenta = new ControlCuenta();

        cuentasImagenes = Ccuenta.TraerCuentasImagenes();

        //***************************************************************************************************************************************
        String data[][] = {};
        String Cabeza[] = {"NombreCuenta", "Nombres", "Nombre imagen", "Fecha subida", "Formato imagen", "Resolución", "Categoría"};

        tablaCuentasImagenes = new DefaultTableModel(data, Cabeza);

        jTableCuentas.setModel(tablaCuentasImagenes);

        //***************************************************************************************************************************************
        for (int i = 0; i < cuentasImagenes.size(); i++) {

            String Datos[] = cuentasImagenes.get(i).split(",");

            String NombreU = Datos[0];
            String NombreCuenta = Datos[1];
            String NombreI = Datos[2];
            String FechaSubidaI = Datos[3];
            String FormatoI = Datos[4];
            String Resolucion = Datos[5];
            String Categoria = Datos[6];

            String datos[] = {NombreU, NombreCuenta, NombreI, FechaSubidaI, FormatoI, Resolucion, Categoria};
            tablaCuentasImagenes.addRow(datos);

        }//Fin for

        Mostrar1.setEnabled(false);
    }//GEN-LAST:event_Mostrar1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        nombreCategoria = NombreC.getText();

        listaCategorias.addElement(nombreCategoria);

        ControlCategoria cCategoria = new ControlCategoria();

        boolean t = cCategoria.InsertarCategoria(nombreCategoria);

        if (t) {

            JOptionPane.showMessageDialog(null, "Categoría guardada.");
            NombreC.setText("");

        }//Fin if

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        int posicionLista = ListaCategorias.getSelectedIndex();

        String pkCategoria = "";

        //Se trae el nombre de la categoría 
        String NameCategoria = ListaCategorias.getSelectedValue();

        int Respuesta = JOptionPane.showConfirmDialog(null, "¿Desea eliminar la categoría " + NameCategoria + "?");

        if (Respuesta == 0) {

            ControlCategoria Ccategoria = new ControlCategoria();

            for (int i = 0; i < categoriasRegistradas.size(); i++) {

                if (NameCategoria.equals(categoriasRegistradas.get(i).getNombreCategoria())) {

                    pkCategoria = categoriasRegistradas.get(i).getCodigoCategoria();

                }//Fin if

            }//Fin for

            boolean t = Ccategoria.EliminarCategoria(pkCategoria);

            if (t) {

                listaCategorias.remove(posicionLista);
                JOptionPane.showMessageDialog(null, "Categoría [ " + NameCategoria + " ] ha sido eliminado.");

            }//Fin if

        }//Fin if principal

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        String Nombrecategoria = ListaCategorias.getSelectedValue();
        int PosicionCategoria = ListaCategorias.getSelectedIndex();

        String ValorActualizar = JOptionPane.showInputDialog(null, "Introducir valor a actualizar: ");

        String pkCategoria = "";

        for (int i = 0; i < categoriasRegistradas.size(); i++) {

            if (Nombrecategoria.equals(categoriasRegistradas.get(i).getNombreCategoria())) {

                pkCategoria = categoriasRegistradas.get(i).getCodigoCategoria();

            }//Fin if

        }//Fin for

        ControlCategoria cCategoria = new ControlCategoria();

        boolean t = cCategoria.ActualizarCategoria(pkCategoria, ValorActualizar);

        if (t) {

            JOptionPane.showMessageDialog(null, "Categoría actualizada.");
            listaCategorias.setElementAt(ValorActualizar, PosicionCategoria);

        }//Fin if

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        GUIcuenta = new Cuenta();
        GUIcuenta.show();
        this.dispose();

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        System.exit(0);

    }//GEN-LAST:event_jButton11ActionPerformed

    private void Mostrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar2ActionPerformed

        ControlCuenta Ccuenta = new ControlCuenta();

        cuentasVideos = Ccuenta.TraerCuentasVideo();

        String data[][] = {};
        String Cabeza[] = {"NombreCuenta", "Nombres", "Nombre video", "Fecha subida", "Formato video", "Duración video", "Categoría"};

        tablaCuentasVideos = new DefaultTableModel(data, Cabeza);

        jTableCuentaVideos.setModel(tablaCuentasVideos);

        //***************************************************************************************************************************************
        for (int i = 0; i < cuentasVideos.size(); i++) {

            String Datos[] = cuentasVideos.get(i).split(",");

            String NombreU = Datos[0];
            String NombreCuenta = Datos[1];
            String NombreV = Datos[2];
            String FechaSubidaV = Datos[3];
            String FormatoV = Datos[4];
            String Duracion = Datos[5];
            String Categoria = Datos[6];

            String datos[] = {NombreU, NombreCuenta, NombreV, FechaSubidaV, FormatoV, Duracion, Categoria};
            tablaCuentasVideos.addRow(datos);

        }//Fin for

        Mostrar2.setEnabled(false);

    }//GEN-LAST:event_Mostrar2ActionPerformed

    private void Mostrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar3ActionPerformed

        ControlCuenta Ccuenta = new ControlCuenta();

        cuentasAudios = Ccuenta.TraerCuentasAudios();

        //***************************************************************************************************************************************
        String data[][] = {};
        String Cabeza[] = {"NombreCuenta", "Nombres", "Nombre video", "Fecha subida", "Formato video", "Tamaño audio", "Duración", "Categoría"};

        tablaCuentasAudios = new DefaultTableModel(data, Cabeza);

        jTableCuentaAudios.setModel(tablaCuentasAudios);

        for (int i = 0; i < cuentasAudios.size(); i++) {

            String Datos[] = cuentasAudios.get(i).split(",");

            String NombreU = Datos[0];
            String NombreCuenta = Datos[1];
            String NombreA = Datos[2];
            String FechaSubidaA = Datos[3];
            String FormatoA = Datos[4];
            String TamañoA = Datos[5];
            String DuracionA = Datos[6];
            String Categoria = Datos[7];

            String datos[] = {NombreU, NombreCuenta, NombreA, FechaSubidaA, FormatoA, TamañoA, DuracionA, Categoria};
            tablaCuentasAudios.addRow(datos);

        }//Fin for

        Mostrar3.setEnabled(false);

    }//GEN-LAST:event_Mostrar3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (ContenidosComentarios.isEmpty() == false) {

            ContenidosComentarios.clear();

        }//Fin if

        ControlImagen Cimagen = new ControlImagen();

        ContenidosComentarios = Cimagen.TraerImagenesComentarios();

        String data[][] = {};
        String Cabeza[] = {"Descripcion Comentario", "Fecha publicación comentario", "Nombre Usuario publicación", "Nombre Imagen", "Fecha subida Imagen"};

        tablaContenidoComentarios = new DefaultTableModel(data, Cabeza);

        jTableContenidoComentarios.setModel(tablaContenidoComentarios);

        for (int i = 0; i < ContenidosComentarios.size(); i++) {

            String Datos[] = ContenidosComentarios.get(i).split(";");

            String DescripcionC = Datos[0];
            String FechaP = Datos[1];
            String NombreU = Datos[2];
            String NombreI = Datos[3];
            String FechaS = Datos[4];

            String datos[] = {DescripcionC, FechaP, NombreU, NombreI, FechaS};
            tablaContenidoComentarios.addRow(datos);

        }//Fin for

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (ContenidosComentarios.isEmpty() == false) {

            ContenidosComentarios.clear();

        }//Fin if

        ControlAudio Caudio = new ControlAudio();

        ContenidosComentarios = Caudio.TraerAudiosComentarios();

        String data[][] = {};
        String Cabeza[] = {"Descripcion Comentario", "Fecha publicación comentario", "Nombre Usuario publicación", "Nombre Audio", "Fecha subida Audio"};

        tablaContenidoComentarios = new DefaultTableModel(data, Cabeza);

        jTableContenidoComentarios.setModel(tablaContenidoComentarios);

        for (int i = 0; i < ContenidosComentarios.size(); i++) {

            String Datos[] = ContenidosComentarios.get(i).split(";");

            String DescripcionC = Datos[0];
            String FechaP = Datos[1];
            String NombreU = Datos[2];
            String NombreA = Datos[3];
            String FechaS = Datos[4];

            String datos[] = {DescripcionC, FechaP, NombreU, NombreA, FechaS};
            tablaContenidoComentarios.addRow(datos);

        }//Fin for        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (ContenidosComentarios.isEmpty() == false) {

            ContenidosComentarios.clear();

        }//Fin if

        ControlVideo CVideo = new ControlVideo();

        ContenidosComentarios = CVideo.TraerVideosComentarios();

        String data[][] = {};
        String Cabeza[] = {"Descripcion Comentario", "Fecha publicación comentario", "Nombre Usuario publicación", "Nombre Video", "Fecha subida Video"};

        tablaContenidoComentarios = new DefaultTableModel(data, Cabeza);

        jTableContenidoComentarios.setModel(tablaContenidoComentarios);

        for (int i = 0; i < ContenidosComentarios.size(); i++) {

            String Datos[] = ContenidosComentarios.get(i).split(";");

            String DescripcionC = Datos[0];
            String FechaP = Datos[1];
            String NombreU = Datos[2];
            String NombreV = Datos[3];
            String FechaS = Datos[4];

            String datos[] = {DescripcionC, FechaP, NombreU, NombreV, FechaS};
            tablaContenidoComentarios.addRow(datos);

        }//Fin for

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    public void DesplegarCategorias() {

        ControlCategoria Ccategoria = new ControlCategoria();

        categoriasRegistradas = Ccategoria.LeerCategorias();

        //Se válida que el linkedList no esté vacío
        //Con el propósito de evitar exception
        if (categoriasRegistradas.isEmpty() == false) {

            for (int i = 0; i < categoriasRegistradas.size(); i++) {

                listaCategorias.addElement(categoriasRegistradas.get(i).getNombreCategoria());

            }//Fin for

        }//Fin if

    }//Fin método

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaCategorias;
    private javax.swing.JButton Mostrar1;
    private javax.swing.JButton Mostrar2;
    private javax.swing.JButton Mostrar3;
    private javax.swing.JTextField NombreC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTableContenidoComentarios;
    private javax.swing.JTable jTableCuentaAudios;
    private javax.swing.JTable jTableCuentaVideos;
    private javax.swing.JTable jTableCuentas;
    // End of variables declaration//GEN-END:variables
}
