/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlAudio;
import Control.ControlCategoria;
import Control.ControlComentarioAudio;

import Control.ControlCuenta;
import Modelo.Audio;
import Modelo.Categoria;
import Modelo.ComentarioAudio;
import Modelo.CuentaUsuario;

import java.awt.Image;
import java.awt.TextField;
import java.io.File;
import java.io.FileOutputStream;
import java.util.Calendar;
import java.util.LinkedList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Julian Escobar
 */
public class BusquedaAudios extends javax.swing.JFrame {

    Principal GUIprincipal10;
    FileOutputStream salida;

    LinkedList<Audio> audiosGuardados;
    LinkedList<Audio> audiosPalabraBuscar;
    LinkedList<Categoria> categoriasAudios;
    LinkedList<Audio> audiosCategoriasBuscar;
    LinkedList<ComentarioAudio> comentariosAudios;

    String nombreUsuarioBusquedadA;
    String fechaPublicacionC;
    String Pclave;
    String categoriaSeleccionada;

    int contador;
    int contadorAudio;
    int contadorComentario;
    int contadorDescarga;

    int entrar;
    int entrar2;
    int parar;

    boolean cambio = true;

    //*******************************************************
    public BusquedaAudios(String NombreUsuarioBA) {

        initComponents();
        this.setLocationRelativeTo(this);
        nombreUsuarioBusquedadA = NombreUsuarioBA;

        audiosGuardados = new LinkedList<>();
        audiosPalabraBuscar = new LinkedList<>();
        categoriasAudios = new LinkedList<>();
        audiosCategoriasBuscar = new LinkedList<>();
        comentariosAudios = new LinkedList<>();

        contador = 0;
        contadorAudio = 1;
        contadorComentario = 0;
        contadorDescarga = 0;

        Pclave = "";
        categoriaSeleccionada = "Categorias";
        entrar = 0;
        entrar2 = 0;
        parar = 0;
        TextComentario.setEnabled(false);
        TraerAudios();
        TraerCategorias();
        TraerCuenta();

        //****************************************************************************
        if (cambio) {

            MostrarAudios();
            traerComentarios(audiosGuardados.get(contador).getIdContenidoA());
            if (comentariosAudios.isEmpty() == false) {

                CrearEspaciosComentarios();
                ValidarBotonesComentario();
                //DerechaComentario.setEnabled(true);

            } else {

                //IzquierdaComentario.setEnabled(false);
                //DerechaComentario.setEnabled(false);
            }//Fin if

            jLabelContador.setText("/" + String.valueOf(audiosGuardados.size()));
            BotonIzquierda.setEnabled(false);
            Contador.setText(String.valueOf(contadorAudio));

            mostrar.setEnabled(false);
            cambio = false;

        }//Fin if

    }

    public BusquedaAudios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelAudio = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Contador = new javax.swing.JTextField();
        jLabelContador = new javax.swing.JLabel();
        BotonIzquierda = new javax.swing.JButton();
        BotonDerecha = new javax.swing.JButton();
        categorias = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelPerfilCuenta = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        comentario = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DescripcionA = new javax.swing.JTextArea();
        CategoriaA = new javax.swing.JTextField();
        FormatoA = new javax.swing.JTextField();
        NombreA = new javax.swing.JTextField();
        duracionHoras = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        FechaSubida = new javax.swing.JTextField();
        duracionMinutos = new javax.swing.JTextField();
        duracionSegundos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TamanoA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelFotoP = new javax.swing.JLabel();
        jLabelNombreU = new javax.swing.JLabel();
        Descargar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        Buscar = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        AgregarComentario = new javax.swing.JButton();
        mostrar = new javax.swing.JButton();
        pClave = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextComentario = new javax.swing.JTextArea();
        editarC = new javax.swing.JButton();
        eliminarC = new javax.swing.JButton();
        guardarC = new javax.swing.JButton();
        IzquierdaComentario = new javax.swing.JButton();
        DerechaComentario = new javax.swing.JButton();
        jLabelFotoC = new javax.swing.JLabel();
        NUsuario = new javax.swing.JLabel();
        fPublicacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAudio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Contador.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelContador.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelContador.setText("/0");

        BotonIzquierda.setText("<");
        BotonIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIzquierdaActionPerformed(evt);
            }
        });

        BotonDerecha.setText(">");
        BotonDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDerechaActionPerformed(evt);
            }
        });

        categorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categorias" }));

        jLabelPerfilCuenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        comentario.setColumns(20);
        comentario.setRows(5);
        jScrollPane2.setViewportView(comentario);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Formato Audio");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nombre Audio");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Duración");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Categoría");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Descripción");

        DescripcionA.setColumns(20);
        DescripcionA.setRows(5);
        DescripcionA.setEnabled(false);
        jScrollPane3.setViewportView(DescripcionA);

        CategoriaA.setEnabled(false);

        FormatoA.setEnabled(false);

        NombreA.setEnabled(false);

        duracionHoras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        duracionHoras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duracionHoras.setText("05");
        duracionHoras.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Fecha subida");

        FechaSubida.setEnabled(false);

        duracionMinutos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        duracionMinutos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duracionMinutos.setText("05");
        duracionMinutos.setEnabled(false);

        duracionSegundos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        duracionSegundos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duracionSegundos.setText("05");
        duracionSegundos.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText(":");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText(":");

        TamanoA.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tamaño");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(FormatoA, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NombreA, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(duracionHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12)
                        .addGap(8, 8, 8)
                        .addComponent(duracionMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel13)
                        .addGap(8, 8, 8)
                        .addComponent(duracionSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CategoriaA, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FechaSubida, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TamanoA, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(FormatoA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(NombreA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(duracionHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duracionMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duracionSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TamanoA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaSubida, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoriaA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelFotoP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNombreU.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNombreU.setText("Nombre Usuario");

        Descargar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Descargar.setText("DESCARGAR AUDIO");
        Descargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescargarActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        AgregarComentario.setText("Agregar comentario");
        AgregarComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarComentarioActionPerformed(evt);
            }
        });

        mostrar.setText("Mostrar audios");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Máximo 150 caracteres para el comentario");

        TextComentario.setColumns(20);
        TextComentario.setRows(5);
        jScrollPane4.setViewportView(TextComentario);

        editarC.setText("Editar");
        editarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCActionPerformed(evt);
            }
        });

        eliminarC.setText("Eliminar");
        eliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCActionPerformed(evt);
            }
        });

        guardarC.setText("Guardar");
        guardarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCActionPerformed(evt);
            }
        });

        IzquierdaComentario.setText("<");
        IzquierdaComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzquierdaComentarioActionPerformed(evt);
            }
        });

        DerechaComentario.setText(">");
        DerechaComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DerechaComentarioActionPerformed(evt);
            }
        });

        jLabelFotoC.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        NUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NUsuario.setText("NombreUsuario");

        fPublicacion.setText("FechaPublicación");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabelFotoC, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(NUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fPublicacion))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(IzquierdaComentario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(DerechaComentario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editarC)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(eliminarC)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(guardarC))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NUsuario)
                            .addComponent(fPublicacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelFotoC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarC)
                    .addComponent(editarC)
                    .addComponent(eliminarC)
                    .addComponent(IzquierdaComentario)
                    .addComponent(DerechaComentario))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(categorias, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pClave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Regresar)
                        .addGap(163, 163, 163)
                        .addComponent(Contador, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelContador)
                        .addGap(31, 31, 31)
                        .addComponent(BotonIzquierda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonDerecha))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelPerfilCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AgregarComentario))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Descargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelFotoP, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNombreU)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator3)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonDerecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonIzquierda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Contador, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContador)
                    .addComponent(categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar)
                    .addComponent(Regresar)
                    .addComponent(mostrar)
                    .addComponent(pClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPerfilCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgregarComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNombreU)
                                .addGap(64, 64, 64)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelFotoP, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Descargar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarComentarioActionPerformed

        Calendar c1 = Calendar.getInstance();

        ControlComentarioAudio CcomentarioA = new ControlComentarioAudio();

        String PkAudio = audiosGuardados.get(contador).getIdContenidoA();

        //*************************************************************************************
        //Se obtiene el año, mes y día en el momento en que se crea la cuenta
        String Dia = Integer.toString(c1.get(Calendar.DATE));
        String Mes = Integer.toString(c1.get(Calendar.MONTH) + 1);
        String Año = Integer.toString(c1.get(Calendar.YEAR));

        //Se obtiene la hora, los minutos y los segundos en el momento en que se inserta el comentario
        String Hora = Integer.toString(c1.get(Calendar.HOUR));
        String Minutos = Integer.toString(c1.get(Calendar.MINUTE));
        String Segundos = Integer.toString(c1.get(Calendar.SECOND));

        if (Segundos.length() == 1) {

            Segundos = "0" + Segundos;

        }//Fin if

        fechaPublicacionC = Año.substring(2, 4) + "-0" + Mes + "-" + Dia + " " + Hora + ":" + Minutos + ":" + Segundos;
        String descripcionComentario = comentario.getText();

        if (descripcionComentario.equals("")) {

            JOptionPane.showMessageDialog(null, "Añadir una descripción al comentario.", "Advertencia", JOptionPane.ERROR_MESSAGE);

        } else {

            //Se crea el objeto comentarioImagen
            ComentarioAudio CA = new ComentarioAudio(fechaPublicacionC, descripcionComentario);

            //*************************************************************************************
            boolean t = CcomentarioA.InsertarComentario(PkAudio, nombreUsuarioBusquedadA, CA);

            if (t) {

                JOptionPane.showMessageDialog(null, "Comentario agregado.");
                comentario.setText("");

            }//Fin if

        }//Fin if principal

    }//GEN-LAST:event_AgregarComentarioActionPerformed

    private void BotonDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDerechaActionPerformed

        TextComentario.setEnabled(false);

        if (Pclave.equals("") && categoriaSeleccionada.equals("Categorias")) {

            if (contador < (audiosGuardados.size() - 1)) {

                contador = 1 + contador;
                MostrarAudios();
                BotonIzquierda.setEnabled(true);

                //******************************************************************
                contadorAudio = 1 + contadorAudio;
                Contador.setText(String.valueOf(contadorAudio));

                //******************************************************************
                //Método que actualiza los comentarios del audio cada vez que se haga un cambio
                //de búsqueda
                ActualizarComentariosGUI();

            } else {

                //Se desactiva el botón derecha cuando se llegue al máximo de audios guardados
                //en el linkedList
                BotonDerecha.setEnabled(false);

            }//Fin if

        } else if (!"".equals(Pclave)) {

            if (contador < (audiosPalabraBuscar.size() - 1)) {

                contador = 1 + contador;
                MostrarAudiosPalabraBusquedad();
                BotonIzquierda.setEnabled(true);
                ActualizarComentariosGUIPalabraClave();

                //******************************************************************
                contadorAudio = 1 + contadorAudio;
                Contador.setText(String.valueOf(contadorAudio));

            } else {

                BotonDerecha.setEnabled(false);

            }//Fin if

        } else if (!"Categorias".equals(categoriaSeleccionada)) {

            if (contador < (audiosCategoriasBuscar.size() - 1)) {

                contador = 1 + contador;
                MostrarAudiosCategoriaSeleccionada();
                ActualizarComentariosGUICategoriaBusqueda();
                BotonIzquierda.setEnabled(true);

                //******************************************************************
                contadorAudio = 1 + contadorAudio;
                Contador.setText(String.valueOf(contadorAudio));

            } else {

                BotonDerecha.setEnabled(false);

            }//Fin if

        }//Fin if

    }//GEN-LAST:event_BotonDerechaActionPerformed

    private void BotonIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIzquierdaActionPerformed

        TextComentario.setEnabled(false);

        if (Pclave.equals("") && categoriaSeleccionada.equals("Categorias")) {

            if (contador > 0) {

                contador = contador - 1;
                MostrarAudios();
                BotonDerecha.setEnabled(true);

                //******************************************************************
                contadorAudio = contadorAudio - 1;
                Contador.setText(String.valueOf(contadorAudio));

                //******************************************************************
                //Método que actualiza los comentarios del audio cada vez que se haga un cambio
                //de búsqueda
                ActualizarComentariosGUI();

                //******************************************************************
            } else if (contador == 0) {

                BotonIzquierda.setEnabled(false);

            }//Fin if

        } else if (!"".equals(Pclave)) {

            if (contador > 0) {

                contador = contador - 1;
                MostrarAudiosPalabraBusquedad();
                ActualizarComentariosGUIPalabraClave();
                BotonDerecha.setEnabled(true);

                //******************************************************************
                contadorAudio = contadorAudio - 1;
                Contador.setText(String.valueOf(contadorAudio));

            } else if (contador == 0) {

                BotonIzquierda.setEnabled(false);

            }//Fin if

        } else if (!"Categorias".equals(categoriaSeleccionada)) {

            if (contador > 0) {

                contador = contador - 1;
                MostrarAudiosCategoriaSeleccionada();
                ActualizarComentariosGUICategoriaBusqueda();
                BotonDerecha.setEnabled(true);

                //******************************************************************
                contadorAudio = contadorAudio - 1;
                Contador.setText(String.valueOf(contadorAudio));

            } else if (contador == 0) {

                BotonIzquierda.setEnabled(false);

            }//Fin if

        }//Fin if

    }//GEN-LAST:event_BotonIzquierdaActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed

        GUIprincipal10 = new Principal();
        GUIprincipal10.setNombreUsuarioPrincipal(nombreUsuarioBusquedadA);
        GUIprincipal10.show();
        this.dispose();

    }//GEN-LAST:event_RegresarActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed

        Pclave = "";
        categoriaSeleccionada = "Categorias";
        MostrarAudios();
        //Se reinicia las variables que traen los datos de cada imagen que fueron asignados a los linkedList
        contador = 0;
        contadorAudio = 1;

        jLabelContador.setText("/" + String.valueOf(audiosGuardados.size()));
        BotonIzquierda.setEnabled(false);
        Contador.setText(String.valueOf(contadorAudio));

        //Se actualizan los botones
        BotonIzquierda.setEnabled(false);
        BotonDerecha.setEnabled(true);

    }//GEN-LAST:event_mostrarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed

        TextComentario.setEnabled(false);

        //***************************************************************************************************************************
        Pclave = pClave.getText();
        categoriaSeleccionada = categorias.getSelectedItem().toString();

        if (Pclave.equals("") && categoriaSeleccionada.equals("Categorias")) {

            JOptionPane.showMessageDialog(null, "Seleccionar un método de búsqueda." + "\n\nMétodos:" + "\n1.Buscar por palabra clave." + "\n2.Buscar por categorías.", "Advertencia", JOptionPane.ERROR_MESSAGE);

        } else {

            if (!"".equals(Pclave)) {

                if (audiosPalabraBuscar.isEmpty() == false) {

                    audiosPalabraBuscar.clear();

                }//Fin if

                AudiosPalabraclave();

                //******************************************************************************************************
                if (audiosPalabraBuscar.isEmpty() == false) {

                    //Se reinicia las variables que traen los datos de cada video que fueron asignados a los linkedList
                    contador = 0;
                    contadorAudio = 1;

                    MostrarAudiosPalabraBusquedad();
                    ActualizarComentariosGUIPalabraClave();

                    jLabelContador.setText("/" + String.valueOf(audiosPalabraBuscar.size()));
                    BotonIzquierda.setEnabled(false);
                    Contador.setText(String.valueOf(contadorAudio));
                    mostrar.setEnabled(true);

                    //Se actualizan los botones
                    BotonIzquierda.setEnabled(false);
                    BotonDerecha.setEnabled(true);

                    //Se actualizan las variables
                    categoriaSeleccionada = "Categorias";
                    pClave.setText("");

                } else {

                    Pclave = "";
                    //Se actualizan las variables
                    categoriaSeleccionada = "Categorias";
                    pClave.setText("");

                }//Fin if

            } else if (!"Categorias".equals(categoriaSeleccionada)) {

                if (audiosCategoriasBuscar.isEmpty() == false) {

                    audiosCategoriasBuscar.clear();

                }//Fin if

                AudiosCategoriaBusquedad();

                //******************************************************************************************************
                if (audiosCategoriasBuscar.isEmpty() == false) {

                    //Se reinicia las variables que traen los datos de cada imagen que fueron asignados a los linkedList
                    contador = 0;
                    contadorAudio = 1;

                    MostrarAudiosCategoriaSeleccionada();
                    //Es importante invocar el método después de que se reinicie el contador general 
                    //Pues si se coloca antes, tomará el último valor del contador registrado
                    //Generando que salga error con el tamaño de algún linkedList al invocarse
                    //El método de actualizar los comentarios cuando la búsqueda es por categorías
                    ActualizarComentariosGUICategoriaBusqueda();

                    jLabelContador.setText("/" + String.valueOf(audiosCategoriasBuscar.size()));
                    BotonIzquierda.setEnabled(false);
                    Contador.setText(String.valueOf(contadorAudio));
                    mostrar.setEnabled(true);

                    //Se actualizan los botones
                    BotonIzquierda.setEnabled(false);
                    BotonDerecha.setEnabled(true);

                    //Se actualizan las variables
                    Pclave = "";
                    categorias.setSelectedItem("Categorias");

                } else {

                    categoriaSeleccionada = "Categorias";

                    //Se actualizan las variables
                    Pclave = "";
                    categorias.setSelectedItem("Categorias");

                }//Fin if

            }//Fin if

        }//Fin if principal

    }//GEN-LAST:event_BuscarActionPerformed

    private void DescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescargarActionPerformed

        if (Pclave.equals("") && categoriaSeleccionada.equals("Categorias")) {

            Descarga(audiosGuardados.get(contador).getArchivoAudio(), audiosGuardados.get(contador).getNombreAudio(), audiosGuardados.get(contador).getFormato_Audio());

        } else if (!"".equals(Pclave)) {

            Descarga(audiosPalabraBuscar.get(contador).getArchivoAudio(), audiosPalabraBuscar.get(contador).getNombreAudio(), audiosPalabraBuscar.get(contador).getFormato_Audio());

        } else if (!"Categorias".equals(categoriaSeleccionada)) {

            Descarga(audiosCategoriasBuscar.get(contador).getArchivoAudio(), audiosCategoriasBuscar.get(contador).getNombreAudio(), audiosCategoriasBuscar.get(contador).getFormato_Audio());

        }//Fin método

    }//GEN-LAST:event_DescargarActionPerformed

    private void DerechaComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DerechaComentarioActionPerformed

        if (contadorComentario < (comentariosAudios.size() - 1)) {

            contadorComentario = 1 + contadorComentario;
            CrearEspaciosComentarios();
            //IzquierdaComentario.setEnabled(true);

            ValidarBotonesComentario();

        } else {

            //DerechaComentario.setEnabled(false);
        }//Fin if

    }//GEN-LAST:event_DerechaComentarioActionPerformed

    private void IzquierdaComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzquierdaComentarioActionPerformed

        if (contadorComentario > 0) {

            contadorComentario = contadorComentario - 1;
            CrearEspaciosComentarios();

            //DerechaComentario.setEnabled(true);
            ValidarBotonesComentario();

        } else if (contadorComentario == 0) {

            //IzquierdaComentario.setEnabled(false);
        }//Fin if
    }//GEN-LAST:event_IzquierdaComentarioActionPerformed

    private void editarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCActionPerformed

        TextComentario.setEnabled(true);

    }//GEN-LAST:event_editarCActionPerformed

    private void guardarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCActionPerformed

        int Respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro/a que desea editar el comentario?");

        if (Respuesta == 0) {

            ControlComentarioAudio cCimagen = new ControlComentarioAudio();

            Calendar c1 = Calendar.getInstance();

            String Dia = Integer.toString(c1.get(Calendar.DATE));
            String Mes = Integer.toString(c1.get(Calendar.MONTH) + 1);
            String Año = Integer.toString(c1.get(Calendar.YEAR));

            fechaPublicacionC = Año.substring(2, 4) + "-0" + Mes + "-" + Dia;

            String actualizarComentario = TextComentario.getText();

            //Se actualizar el comentario también en el linkedList
            comentariosAudios.get(contadorComentario).setDescripcionComentario(actualizarComentario);
            comentariosAudios.get(contadorComentario).setFechaPublicacion(fechaPublicacionC + " 00:00:00");

            ComentarioAudio Caudio = new ComentarioAudio(fechaPublicacionC, actualizarComentario);

            boolean t = cCimagen.ModificarComentario(comentariosAudios.get(contadorComentario).getIdComentario(), Caudio);

            if (t) {

                JOptionPane.showMessageDialog(null, "Comentario modificado.");

            }//Fin if

        }//Fin if

    }//GEN-LAST:event_guardarCActionPerformed

    private void eliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCActionPerformed

        int Respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro/a que desea eliminar el comentario?");

        if (Respuesta == 0) {

            ControlComentarioAudio cCaudio = new ControlComentarioAudio();

            boolean t = cCaudio.EliminarComentario(comentariosAudios.get(contadorComentario).getIdComentario(), nombreUsuarioBusquedadA);

            if (t) {

                JOptionPane.showMessageDialog(null, "Comentario eliminado.");
                //Al momento de removerse el comentario en la BD también se remueve el objeto guardado en el linkedList
                comentariosAudios.remove(contadorComentario);
                TextComentario.setText("");
                jLabelFotoC.setIcon(null);
                NUsuario.setText("");
                fPublicacion.setText("");

            }//Fin if

        }//Fin if

    }//GEN-LAST:event_eliminarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaAudios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaAudios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaAudios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaAudios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusquedaAudios().setVisible(true);
            }
        });
    }

    public void TraerAudios() {

        ControlAudio CA = new ControlAudio();

        //Devuelve un linkelist donde se encuentra guardado todos los datos de los audios de varias cuentas
        audiosGuardados = CA.BuscarAudiosGuardados();

    }//Fin método

    public void MostrarAudios() {

        FormatoA.setText(audiosGuardados.get(contador).getFormato_Audio());
        NombreA.setText(audiosGuardados.get(contador).getNombreAudio());
        String duracion = audiosGuardados.get(contador).getDuracionAudio();
        String[] DuracionTotal = duracion.split(":");

        duracionHoras.setText(DuracionTotal[0]);
        duracionMinutos.setText(DuracionTotal[1]);
        duracionSegundos.setText(DuracionTotal[2]);

        CategoriaA.setText(audiosGuardados.get(contador).getCategoriaAudio());
        DescripcionA.setText(audiosGuardados.get(contador).getDescripcionAudio());
        FechaSubida.setText(audiosGuardados.get(contador).getFechaSubidaA());
        TamanoA.setText(audiosGuardados.get(contador).getTamanoAudio());

        jLabelNombreU.setText(audiosGuardados.get(contador).getNombreUsuarioPK());

        ImageIcon icon = new ImageIcon(BusquedaAudios.class.getResource("/Imagenes/audio.png"));
        ImageIcon icon3 = new ImageIcon(audiosGuardados.get(contador).getImagenUsuario());

        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(jLabelAudio.getWidth(), jLabelAudio.getHeight(), Image.SCALE_DEFAULT));
        Icon icono3 = new ImageIcon(icon3.getImage().getScaledInstance(jLabelFotoP.getWidth(), jLabelFotoP.getHeight(), Image.SCALE_DEFAULT));

        jLabelAudio.setIcon(icono);
        jLabelFotoP.setIcon(icono3);

    }//Fin método

    public void MostrarAudiosPalabraBusquedad() {

        FormatoA.setText(audiosPalabraBuscar.get(contador).getFormato_Audio());
        NombreA.setText(audiosPalabraBuscar.get(contador).getNombreAudio());

        String duracion = audiosGuardados.get(contador).getDuracionAudio();
        String[] DuracionTotal = duracion.split(":");

        duracionHoras.setText(DuracionTotal[0]);
        duracionMinutos.setText(DuracionTotal[1]);
        duracionSegundos.setText(DuracionTotal[2]);

        CategoriaA.setText(audiosPalabraBuscar.get(contador).getCategoriaAudio());
        DescripcionA.setText(audiosPalabraBuscar.get(contador).getDescripcionAudio());
        FechaSubida.setText(audiosPalabraBuscar.get(contador).getFechaSubidaA());
        TamanoA.setText(audiosPalabraBuscar.get(contador).getTamanoAudio());

        jLabelNombreU.setText(audiosPalabraBuscar.get(contador).getNombreUsuarioPK());

        //Se pasa la imagen que está en un arreglo de byte para convertirlo en un icono
        ImageIcon icon = new ImageIcon(BusquedaAudios.class.getResource("/Imagenes/audio.png"));
        ImageIcon icon2 = new ImageIcon(audiosPalabraBuscar.get(contador).getImagenUsuario());

        //Después de que la imagen está convertida en icono entonces se procede a escalar el icono con el tamaño que conserva el label
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(jLabelAudio.getWidth(), jLabelAudio.getHeight(), Image.SCALE_DEFAULT));
        Icon icono2 = new ImageIcon(icon2.getImage().getScaledInstance(jLabelFotoP.getWidth(), jLabelFotoP.getHeight(), Image.SCALE_DEFAULT));

        //Se coloca la imagen con el tamaño que tiene en el label
        jLabelAudio.setIcon(icono);
        jLabelFotoP.setIcon(icono2);

    }//Fin método

    public void MostrarAudiosCategoriaSeleccionada() {

        FormatoA.setText(audiosCategoriasBuscar.get(contador).getFormato_Audio());
        NombreA.setText(audiosCategoriasBuscar.get(contador).getNombreAudio());

        String duracion = audiosGuardados.get(contador).getDuracionAudio();
        String[] DuracionTotal = duracion.split(":");

        duracionHoras.setText(DuracionTotal[0]);
        duracionMinutos.setText(DuracionTotal[1]);
        duracionSegundos.setText(DuracionTotal[2]);

        CategoriaA.setText(audiosCategoriasBuscar.get(contador).getCategoriaAudio());
        DescripcionA.setText(audiosCategoriasBuscar.get(contador).getDescripcionAudio());
        FechaSubida.setText(audiosCategoriasBuscar.get(contador).getFechaSubidaA());
        TamanoA.setText(audiosCategoriasBuscar.get(contador).getTamanoAudio());

        jLabelNombreU.setText(audiosCategoriasBuscar.get(contador).getNombreUsuarioPK());

        //Se pasa la imagen que está en un arreglo de byte para convertirlo en un icono
        ImageIcon icon = new ImageIcon(BusquedaAudios.class.getResource("/Imagenes/audio.png"));
        ImageIcon iconUsuario = new ImageIcon(audiosCategoriasBuscar.get(contador).getImagenUsuario());

        //Después de que la imagen está convertida en icono entonces se procede a escalar el icono con el tamaño que conserva el label
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(jLabelAudio.getWidth(), jLabelAudio.getHeight(), Image.SCALE_DEFAULT));
        Icon icono2 = new ImageIcon(iconUsuario.getImage().getScaledInstance(jLabelFotoP.getWidth(), jLabelFotoP.getHeight(), Image.SCALE_DEFAULT));

        //Se coloca la imagen con el tamaño que tiene en el label
        jLabelAudio.setIcon(icono);
        jLabelFotoP.setIcon(icono2);

    }//Fin método

    public void AudiosPalabraclave() {

        for (int i = 0; i < audiosGuardados.size(); i++) {

            if (audiosGuardados.get(i).getDescripcionAudio().contains(Pclave)) {

                audiosPalabraBuscar.add(audiosGuardados.get(i));

            }//Fin if

        }//Fin for

        if (audiosPalabraBuscar.isEmpty()) {

            JOptionPane.showMessageDialog(null, "Lo sentimos, no hay aciertos.", "Advertencia", JOptionPane.ERROR_MESSAGE);

        }//Fin if

    }//Fin método

    public void AudiosCategoriaBusquedad() {

        for (int i = 0; i < audiosGuardados.size(); i++) {

            if (audiosGuardados.get(i).getCategoriaAudio().equals(categoriaSeleccionada)) {

                audiosCategoriasBuscar.add(audiosGuardados.get(i));

            }//Fin if

        }//Fin for

    }//Fin método

    public void TraerCategorias() {

        //Se trae todas las categorías pertenecientes a la BD
        ControlCategoria CC2 = new ControlCategoria();

        categoriasAudios = CC2.LeerCategorias();

        for (int i = 0; i < categoriasAudios.size(); i++) {

            categorias.addItem(categoriasAudios.get(i).getNombreCategoria());

        }//Fin for

    }//Fin método

    public void TraerCuenta() {

        CuentaUsuario cUsuario = null;

        ControlCuenta Ccuenta = new ControlCuenta();

        cUsuario = Ccuenta.LeerCuenta(nombreUsuarioBusquedadA);

        byte[] img = cUsuario.getFotoPerfil();

        ImageIcon icon = new ImageIcon(img);

        //Después de que la imagen está convertida en icono entonces se procede a escalar el icono con el tamaño que conserva el label
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(jLabelPerfilCuenta.getWidth(), jLabelPerfilCuenta.getHeight(), Image.SCALE_DEFAULT));

        //Se coloca la imagen con el tamaño que tiene en el label
        jLabelPerfilCuenta.setIcon(icono);

    }//Fin método

    public void CrearEspaciosComentarios() {

        TextComentario.setText(comentariosAudios.get(contadorComentario).getDescripcionComentario());
        fPublicacion.setText(comentariosAudios.get(contadorComentario).getFechaPublicacion());
        NUsuario.setText(comentariosAudios.get(contadorComentario).getNombreUsuarioComentario());

        ImageIcon icon2 = new ImageIcon(comentariosAudios.get(contadorComentario).getFotoUsuarioComentario());

        //Después de que la imagen está convertida en icono entonces se procede a escalar el icono con el tamaño que conserva el label
        Icon icono2 = new ImageIcon(icon2.getImage().getScaledInstance(jLabelFotoC.getWidth(), jLabelFotoC.getHeight(), Image.SCALE_DEFAULT));

        //Se coloca la imagen con el tamaño que tiene en el label
        jLabelFotoC.setIcon(icono2);

        TextComentario.setEnabled(false);

    }//Fin método

    //Trae los comentarios dependiendo de la imagen que esté observando el usuario
    public void traerComentarios(String IdContenido) {

        ControlComentarioAudio CcomentarioA = new ControlComentarioAudio();

        comentariosAudios = CcomentarioA.TraerComentarios(IdContenido);

    }//Fin método

    public void LimpiarCamposComentarios() {

        //Se reinicia los datos cuando se cambia de imagen de búsqueda
        TextComentario.setText("");
        fPublicacion.setText("");
        NUsuario.setText("");
        //IzquierdaComentario.setEnabled(false);
        //DerechaComentario.setEnabled(true);
        contadorComentario = 0;

    }//Fin método

    public void ActualizarComentariosGUI() {

        //Borra todos los comentarios que hay en el linkedList
        //Cada vez que se cambia para buscar otra imagen
        //Siempre y cuando este linkedList tenga datos guardados
        if (comentariosAudios.isEmpty() == false) {

            //Se limpia el anterior LinkedList que contenía comentarios de otra imagen
            comentariosAudios.clear();
            LimpiarCamposComentarios();

            //Se vuelve a llamar para traer los comentarios de la imagen actual
            traerComentarios(audiosGuardados.get(contador).getIdContenidoA());

            if (comentariosAudios.isEmpty() == false) {

                CrearEspaciosComentarios();

            }//Fin if

        } else {

            //Se vuelve a llamar para traer los comentarios de la imagen actual
            traerComentarios(audiosGuardados.get(contador).getIdContenidoA());

            if (comentariosAudios.isEmpty() == false) {

                CrearEspaciosComentarios();

            }//Fin if

        }//Fin if principal

    }//Fin método

    public void ActualizarComentariosGUIPalabraClave() {

        //Borra todos los comentarios que hay en el linkedList
        //Cada vez que se cambia para buscar otro video
        //Siempre y cuando este linkedList tenga datos guardados
        if (comentariosAudios.isEmpty() == false) {

            //Se limpia el anterior LinkedList que contenía comentarios de otro video
            comentariosAudios.clear();
            LimpiarCamposComentarios();

            //Se vuelve a llamar para traer los comentarios del video actual
            traerComentarios(audiosPalabraBuscar.get(contador).getIdContenidoA());

            if (comentariosAudios.isEmpty() == false) {

                CrearEspaciosComentarios();

            }//Fin if

        } else {

            //Se vuelve a llamar para traer los comentarios del video actual
            traerComentarios(audiosPalabraBuscar.get(contador).getIdContenidoA());

            if (comentariosAudios.isEmpty() == false) {

                CrearEspaciosComentarios();

            }//Fin if

        }//Fin if principal

    }//Fin método

    public void ActualizarComentariosGUICategoriaBusqueda() {

        //Borra todos los comentarios que hay en el linkedList
        //Cada vez que se cambia para buscar otro video
        //Siempre y cuando este linkedList tenga datos guardados
        if (comentariosAudios.isEmpty() == false) {

            //Se limpia el anterior LinkedList que contenía comentarios de otro video
            comentariosAudios.clear();
            LimpiarCamposComentarios();

            //Se vuelve a llamar para traer los comentarios del video actual
            traerComentarios(audiosCategoriasBuscar.get(contador).getIdContenidoA());

            if (comentariosAudios.isEmpty() == false) {

                CrearEspaciosComentarios();

            }//Fin if

        } else {

            //Se vuelve a llamar para traer los comentarios del video actual
            traerComentarios(audiosCategoriasBuscar.get(contador).getIdContenidoA());

            if (comentariosAudios.isEmpty() == false) {

                CrearEspaciosComentarios();

            }//Fin if

        }//Fin if principal

    }//Fin método

    //Este método permite habilitar los botones que hay en la zona de comentario
    //Siempre y cuando los comentarios pertenezcan al usuario correspondiente
    public void ValidarBotonesComentario() {

        String nombreU = comentariosAudios.get(contadorComentario).getNombreUsuarioComentario();

        if (nombreU.equals(nombreUsuarioBusquedadA)) {

            editarC.setEnabled(true);
            eliminarC.setEnabled(true);
            guardarC.setEnabled(true);

        } else {

            editarC.setEnabled(false);
            eliminarC.setEnabled(false);
            guardarC.setEnabled(false);

        }//Fin if

    }//Fin método

    public boolean DescargaAudioRuta(File archivo, byte[] audio) {

        boolean mensaje = false;

        try {

            salida = new FileOutputStream(archivo);
            salida.write(audio);

            mensaje = true;

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Fallo en la descarga: " + e, "Error", JOptionPane.ERROR_MESSAGE);

        }//Fin try

        return mensaje;

    }//Fin método

    public void Descarga(byte[] audios, String NombreAudio, String Formato) {

        String barra = File.separator;
        //Se establece la ruta desde la cuenta usuario del ordenador. Después guarda en la carpeta Videos.
        String ubicacion = System.getProperty("user.home") + barra + "Downloads" + barra;

        //El contador es para cambiar el nombre de la imagen cuando sea descargado
        //Pues si no se cambia y el usuario descargar la imagen varias veces
        //Entonces el sistema pedirá al sistema que ya se encuentra un video guardado con ese nombre
        contadorDescarga = 1 + contadorDescarga;

        String valor = Integer.toString(contadorDescarga);

        //Se establece la ruta donde se guardará el video
        File archivo2 = new File(ubicacion + NombreAudio + " (" + valor + ")" + "." + Formato.toLowerCase());

        boolean respuesta = DescargaAudioRuta(archivo2, audios);

        if (respuesta) {

            JOptionPane.showMessageDialog(null, "Audio descargado exitosamente.");

        } else {

            JOptionPane.showMessageDialog(null, "Fallo en la descarga.", "Error", JOptionPane.ERROR_MESSAGE);

        }//Fin if

    }//Fin método


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarComentario;
    private javax.swing.JButton BotonDerecha;
    private javax.swing.JButton BotonIzquierda;
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField CategoriaA;
    private javax.swing.JTextField Contador;
    private javax.swing.JButton DerechaComentario;
    private javax.swing.JButton Descargar;
    private javax.swing.JTextArea DescripcionA;
    private javax.swing.JTextField FechaSubida;
    private javax.swing.JTextField FormatoA;
    private javax.swing.JButton IzquierdaComentario;
    private javax.swing.JLabel NUsuario;
    private javax.swing.JTextField NombreA;
    private javax.swing.JButton Regresar;
    private javax.swing.JTextField TamanoA;
    private javax.swing.JTextArea TextComentario;
    private javax.swing.JComboBox<String> categorias;
    private javax.swing.JTextArea comentario;
    private javax.swing.JTextField duracionHoras;
    private javax.swing.JTextField duracionMinutos;
    private javax.swing.JTextField duracionSegundos;
    private javax.swing.JButton editarC;
    private javax.swing.JButton eliminarC;
    private javax.swing.JLabel fPublicacion;
    private javax.swing.JButton guardarC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAudio;
    private javax.swing.JLabel jLabelContador;
    private javax.swing.JLabel jLabelFotoC;
    private javax.swing.JLabel jLabelFotoP;
    private javax.swing.JLabel jLabelNombreU;
    private javax.swing.JLabel jLabelPerfilCuenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton mostrar;
    private javax.swing.JTextField pClave;
    // End of variables declaration//GEN-END:variables
}
