/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlCategoria;
import Control.ControlComentarioVideo;
import Control.ControlImagen;
import Control.ControlVideo;
import Modelo.Categoria;
import Modelo.ComentarioVideo;
import Modelo.Video;
import java.awt.Image;
import java.util.LinkedList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Gomez
 */
public class DatosVideo extends javax.swing.JFrame {

    LinkedList<Video> videosCuenta;
    LinkedList<Categoria> categoriasVideos;
    LinkedList<ComentarioVideo> comentariosVideos;
    Principal GUIprincipal3;

    int contador;
    byte[] VideoSubido;

    //**************************************************
    String NombreUsuarioVideos;
    String FechaSubida;
    String FormatoActual;
    String NombreVideo;
    String Duracion;
    String CategoriaActual;
    String DescripcionVideo;

    public DatosVideo(String NombreUsuarioV) {

        initComponents();
        this.setLocationRelativeTo(this);
        NombreUsuarioVideos = NombreUsuarioV;

        videosCuenta = new LinkedList<>();
        categoriasVideos = new LinkedList<>();
        comentariosVideos = new LinkedList<>();

        TraerCategorias();

        FechaSubida = null;
        FormatoActual = null;
        NombreVideo = null;
        Duracion = null;
        CategoriaActual = null;
        DescripcionVideo = null;
        contador = 0;
        VideoSubido = null;

        MostrarVideosCuenta();

        formatoActual.setEnabled(false);
        nombreVideo.setEnabled(false);
        formatoVideo.setEnabled(false);
        categoriaActual.setEnabled(false);
        categorias.setEnabled(false);
        duracionHoras.setEnabled(false);
        duracionMinutos.setEnabled(false);
        duracionSegundos.setEnabled(false);
        descripcionVideo.setEnabled(false);
        guardarV.setEnabled(false);

        ImagenPredeterminada();

    }

    public DatosVideo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        LabelVideo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        EliminarVideo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionVideo = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        fechaSubida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nombreVideo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        formatoActual = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        duracionHoras = new javax.swing.JTextField();
        formatoVideo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        categoriaActual = new javax.swing.JTextField();
        categorias = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        editar = new javax.swing.JButton();
        guardarV = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        duracionSegundos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        duracionMinutos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Datos Video");

        LabelVideo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("<<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText(">>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        EliminarVideo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EliminarVideo.setText("Eliminar");
        EliminarVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarVideoActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Descripción Video / Máximo 150 caracteres");

        descripcionVideo.setColumns(20);
        descripcionVideo.setRows(5);
        jScrollPane1.setViewportView(descripcionVideo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Datos");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Fecha subida");

        fechaSubida.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nombre Video");

        nombreVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreVideoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Formato Actual");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Duración");

        duracionHoras.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        duracionHoras.setText("00");
        duracionHoras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                duracionHorasFocusGained(evt);
            }
        });
        duracionHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracionHorasActionPerformed(evt);
            }
        });

        formatoVideo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------------------", "MP4", "MOV" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Formato Video");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Categoría actual");

        categorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------------------" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Categorías");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        guardarV.setText("Guardar");
        guardarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarVActionPerformed(evt);
            }
        });

        jButton6.setText("Regresar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardarV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        duracionSegundos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        duracionSegundos.setText("00");
        duracionSegundos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                duracionSegundosFocusGained(evt);
            }
        });
        duracionSegundos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracionSegundosActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText(":");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText(":");

        duracionMinutos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        duracionMinutos.setText("00");
        duracionMinutos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                duracionMinutosFocusGained(evt);
            }
        });
        duracionMinutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracionMinutosActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Hor");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Min");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Seg");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EliminarVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(LabelVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(nombreVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(formatoVideo, 0, 120, Short.MAX_VALUE)))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9)
                                            .addComponent(categoriaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(duracionHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel12))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(jLabel14)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(jLabel15))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(duracionMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel16))
                                            .addComponent(duracionSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(categorias, 0, 120, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(177, 195, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fechaSubida, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(formatoActual)))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fechaSubida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formatoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(4, 4, 4)
                                .addComponent(nombreVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formatoVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(categorias, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categoriaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(duracionHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(duracionSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(duracionMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(LabelVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EliminarVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1)
                .addGap(4, 4, 4))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed

        activarCampos();

    }//GEN-LAST:event_editarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (contador < (videosCuenta.size() - 1)) {

            contador = 1 + contador;
            categorias.setSelectedIndex(0);
            formatoVideo.setSelectedIndex(0);
            //Se invocaría este método cada vez que se presione el botón >> con el cambio de contador
            //Para traer los datos de las imágenes correspondiente
            //a una cuenta. Claramente, cada invocación actualiza los datos
            MostrarVideos();
            desactivarCampos();

        }//Fin if

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (contador > 0) {

            contador = contador - 1;
            categorias.setSelectedIndex(0);
            formatoVideo.setSelectedIndex(0);
            //Se invocaría este método cada vez que se presione el botón << con el cambio de contador
            //Para traer los datos de las imágenes correspondiente
            //a una cuenta. Claramente, cada invocación actualiza los datos
            MostrarVideos();
            desactivarCampos();

        }//Fin if

    }//GEN-LAST:event_jButton1ActionPerformed

    private void guardarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarVActionPerformed

        ControlVideo CV2 = new ControlVideo();

        NombreVideo = nombreVideo.getText();
        FormatoActual = formatoVideo.getSelectedItem().toString();
        CategoriaActual = categorias.getSelectedItem().toString();
        DescripcionVideo = descripcionVideo.getText();

        String duracion = videosCuenta.get(contador).getDuracionVideo();
        String[] DuracionTotal = duracion.split(":");

        //******************************************************************************************************************
        //CONDICIONES PARA OBTENER EL TIEMPO EN FORMATO 00:00:00
        if (duracionHoras.getText().equals("")) {

            Duracion = "00";

        } else {

            switch (duracionHoras.getText().length()) {

                case 1:

                    Duracion = "0" + duracionHoras.getText();
                    break;

                case 2:

                    Duracion = duracionHoras.getText();
                    break;

                default:

                    JOptionPane.showMessageDialog(null, "Hora no válida", "Advertencia", JOptionPane.ERROR_MESSAGE);
                    Duracion = DuracionTotal[0];
                    duracionHoras.setText(DuracionTotal[0]);
                    break;
            }

        }//Fin if

        if (duracionMinutos.getText().equals("")) {

            Duracion = Duracion + ":00";

        } else {

            if (duracionMinutos.getText().length() == 1) {
                Duracion = Duracion + ":0" + duracionMinutos.getText();

            } else if (duracionMinutos.getText().length() == 2 && Integer.parseInt(duracionMinutos.getText()) <= 60) {

                Duracion = Duracion + ":" + duracionMinutos.getText();

            } else {

                JOptionPane.showMessageDialog(null, "Minutos no válidos", "Advertencia", JOptionPane.ERROR_MESSAGE);
                Duracion = Duracion + ":" + DuracionTotal[1];
                duracionMinutos.setText(DuracionTotal[1]);

            }//Fin segundo if

        }//Fin if

        if (duracionSegundos.getText().equals("")) {

            Duracion = Duracion + ":00";

        } else {

            if (duracionSegundos.getText().length() == 1) {

                Duracion = Duracion + ":0" + duracionSegundos.getText();

            } else if (duracionSegundos.getText().length() == 2 && Integer.parseInt(duracionSegundos.getText()) <= 60) {

                Duracion = Duracion + ":" + duracionSegundos.getText();

            } else {

                JOptionPane.showMessageDialog(null, "Segundos no válidos", "Advertencia", JOptionPane.ERROR_MESSAGE);
                Duracion = Duracion + ":" + DuracionTotal[2];
                duracionSegundos.setText(DuracionTotal[2]);

            }//Fin segundo if

        }//Fin if

        //******************************************************************************************************************
        if (CategoriaActual.equals("----------------------")) {

            CategoriaActual = categoriaActual.getText();

        }//Fin if

        if (FormatoActual.equals("-----------------------")) {

            FormatoActual = formatoActual.getText();

        }//Fin if

        //*************************************************************************************************************************
        //Se actualiza los valores del video, siempre y cuando el usuario haya realizado una actualización desde la aplicación
        videosCuenta.get(contador).setNombreVideo(NombreVideo);
        videosCuenta.get(contador).setFormato_Video(FormatoActual);
        videosCuenta.get(contador).setDuracionVideo(Duracion);
        videosCuenta.get(contador).setDescripcionVideo(DescripcionVideo);

        Video videoActualizar = videosCuenta.get(contador);
        String pkCategoria = "";

        for (int i = 0; i < categoriasVideos.size(); i++) {

            if (categoriasVideos.get(i).getNombreCategoria().equals(CategoriaActual)) {

                pkCategoria = categoriasVideos.get(i).getCodigoCategoria();
                videosCuenta.get(contador).setCategoriaVideo(CategoriaActual);

            }//Fin if

        }//Fin for

        //*************************************************************************************************************************
        boolean t = CV2.ActualizarDatos(videosCuenta.get(contador).getIdContenidoV(), videoActualizar, pkCategoria);

        if (t) {

            JOptionPane.showMessageDialog(null, "Datos actualizados.");

        } else {

            JOptionPane.showMessageDialog(null, "Datos no actualizados.");

        }//Fin if

    }//GEN-LAST:event_guardarVActionPerformed

    private void EliminarVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarVideoActionPerformed

        int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro/a que desea eliminar el video?");

        if (respuesta == 0) {

            ControlVideo CI3 = new ControlVideo();
            ControlComentarioVideo CcomentarioV = new ControlComentarioVideo();

            String IdContenido = videosCuenta.get(contador).getIdContenidoV();
            comentariosVideos = CcomentarioV.TraerComentarios(IdContenido);
            EliminarComentariosVideos();

            boolean t = CI3.EliminarVideo(IdContenido);

            if (t) {

                JOptionPane.showMessageDialog(null, "Datos del video eliminados");
                //Se elimina el objeto de la imagen que quedó en el linkedlist
                videosCuenta.remove(contador);
                LabelVideo.setIcon(null);
                fechaSubida.setText("");
                formatoActual.setText("");
                categoriaActual.setText("");
                duracionHoras.setText("");
                duracionMinutos.setText("");
                duracionSegundos.setText("");
                descripcionVideo.setText("");
                nombreVideo.setText("");
                
                if(comentariosVideos.isEmpty() == false){
                    
                    comentariosVideos.clear();
                    
                }//Fin condición para limpiar el LinkedList

            } else {

                JOptionPane.showMessageDialog(null, "Datos del video no eliminados");

            }//Fin if

        }//Fin if principal

    }//GEN-LAST:event_EliminarVideoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        GUIprincipal3 = new Principal();
        GUIprincipal3.show();
        GUIprincipal3.setNombreUsuarioPrincipal(NombreUsuarioVideos);
        this.dispose();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void duracionMinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracionMinutosActionPerformed

    }//GEN-LAST:event_duracionMinutosActionPerformed

    private void nombreVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreVideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreVideoActionPerformed

    private void duracionHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracionHorasActionPerformed

    }//GEN-LAST:event_duracionHorasActionPerformed

    private void duracionSegundosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracionSegundosActionPerformed

    }//GEN-LAST:event_duracionSegundosActionPerformed

    private void duracionHorasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_duracionHorasFocusGained
        duracionHoras.setText("");
    }//GEN-LAST:event_duracionHorasFocusGained

    private void duracionMinutosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_duracionMinutosFocusGained
        duracionMinutos.setText("");
    }//GEN-LAST:event_duracionMinutosFocusGained

    private void duracionSegundosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_duracionSegundosFocusGained
        duracionSegundos.setText("");
    }//GEN-LAST:event_duracionSegundosFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosVideo().setVisible(true);
            }
        });
    }

    //Método para mostrar los videos en la aplicación
    public void MostrarVideos() {

        fechaSubida.setText(videosCuenta.get(contador).getFechaSubidaV());
        nombreVideo.setText(videosCuenta.get(contador).getNombreVideo());
        formatoActual.setText(videosCuenta.get(contador).getFormato_Video());

        String duracion = videosCuenta.get(contador).getDuracionVideo();
        String[] DuracionTotal = duracion.split(":");

        duracionHoras.setText(DuracionTotal[0]);
        duracionMinutos.setText(DuracionTotal[1]);
        duracionSegundos.setText(DuracionTotal[2]);

        categoriaActual.setText(videosCuenta.get(contador).getCategoriaVideo());

        descripcionVideo.setText(videosCuenta.get(contador).getDescripcionVideo());

        VideoSubido = videosCuenta.get(contador).getVideo();

    }//Fin método

    public void TraerCategorias() {

        ControlCategoria CC = new ControlCategoria();
        categoriasVideos = CC.LeerCategorias();

        for (int i = 0; i < categoriasVideos.size(); i++) {

            categorias.addItem(categoriasVideos.get(i).getNombreCategoria());

        }//Fin for

    }//Fin método

    public void ImagenPredeterminada() {

        ImageIcon icon = new ImageIcon(DatosVideo.class.getResource("/Imagenes/video-icon.jpg"));
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(LabelVideo.getWidth(), LabelVideo.getHeight(), Image.SCALE_DEFAULT));

        LabelVideo.setIcon(icono);

    }//Fin método

    public void MostrarVideosCuenta() {

        ControlVideo CI = new ControlVideo();

        //Devuelve un linkelist donde se encuentra guardado todos los datos de las imagenes de la cuenta
        videosCuenta = CI.TraerVideos(NombreUsuarioVideos);

        if (videosCuenta.isEmpty() == false) {

            MostrarVideos();

            guardarV.setEnabled(true);
            EliminarVideo.setEnabled(true);

        } else {

            JOptionPane.showMessageDialog(null, "No has agregado contenido de video a tu cuenta." + "\n\nNota: puedes agregar videos presionando la pestaña" + "\n[Video] que se encuentra en la ventana principal.");

            EliminarVideo.setEnabled(false);
            guardarV.setEnabled(false);

        }//Fin if

    }//Fin método

    public void activarCampos() {

        nombreVideo.setEnabled(true);
        formatoVideo.setEnabled(true);
        categorias.setEnabled(true);
        duracionHoras.setEnabled(true);
        duracionMinutos.setEnabled(true);
        duracionSegundos.setEnabled(true);
        descripcionVideo.setEnabled(true);
        guardarV.setEnabled(true);

    }//Fin método

    public void desactivarCampos() {

        nombreVideo.setEnabled(false);
        formatoVideo.setEnabled(false);
        categorias.setEnabled(false);
        duracionHoras.setEnabled(false);
        duracionMinutos.setEnabled(false);
        duracionSegundos.setEnabled(false);
        descripcionVideo.setEnabled(false);
        guardarV.setEnabled(false);

    }//Fin método

    public void EliminarComentariosVideos() {

        ControlComentarioVideo cComentarioVideo = new ControlComentarioVideo();

        if (comentariosVideos.isEmpty() == false) {

            for (int i = 0; i < comentariosVideos.size(); i++) {

                cComentarioVideo.EliminarComentariosVideoCuenta(comentariosVideos.get(i).getIdComentario());

            }//Fin for

        }//Fin condición

    }//Fin método

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarVideo;
    private javax.swing.JLabel LabelVideo;
    private javax.swing.JTextField categoriaActual;
    private javax.swing.JComboBox<String> categorias;
    private javax.swing.JTextArea descripcionVideo;
    private javax.swing.JTextField duracionHoras;
    private javax.swing.JTextField duracionMinutos;
    private javax.swing.JTextField duracionSegundos;
    private javax.swing.JButton editar;
    private javax.swing.JTextField fechaSubida;
    private javax.swing.JTextField formatoActual;
    private javax.swing.JComboBox<String> formatoVideo;
    private javax.swing.JButton guardarV;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField nombreVideo;
    // End of variables declaration//GEN-END:variables
}
