/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlCategoria;
import Control.ControlComentarioImagen;
import Control.ControlImagen;
import Modelo.Categoria;
import Modelo.ComentarioImagen;
import Modelo.Imagen;
import java.awt.Image;
import java.util.LinkedList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateo
 */
public class DatosImagen extends javax.swing.JFrame {

    LinkedList<Imagen> imagenesCuenta;
    LinkedList<Categoria> categoriasImagenes;
    LinkedList<ComentarioImagen> comentariosImagenes;
    Principal GUIprincipal3;

    int contador;
    byte[] ImagenSubida;

    //**************************************************
    String NombreUsuarioImagenes;
    String FechaSubida;
    String FormatoActual;
    String NombreImagen;
    String Resolucion;
    String CategoriaActual;
    String DescripcionImagen;

    public DatosImagen(String NombreUsuarioI) {

        initComponents();
        this.setLocationRelativeTo(this);
        NombreUsuarioImagenes = NombreUsuarioI;

        imagenesCuenta = new LinkedList<>();
        categoriasImagenes = new LinkedList<>();
        comentariosImagenes = new LinkedList<>();

        TraerCategorias();

        FechaSubida = null;
        FormatoActual = null;
        NombreImagen = null;
        Resolucion = null;
        CategoriaActual = null;
        DescripcionImagen = null;
        contador = 0;
        ImagenSubida = null;

        TraerImagenesCuenta();

        formatoActual.setEnabled(false);
        formatoImagen.setEnabled(false);
        categorias.setEnabled(false);
        categoriaActual.setEnabled(false);
        nombreImagen.setEnabled(false);
        resolucion.setEnabled(false);
        descripcionImagen.setEnabled(false);
        guardarI.setEnabled(false);

    }

    public DatosImagen() {
        initComponents();
    }

    //********************************************************************
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        LabelImagen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        elminarImagen = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionImagen = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        fechaSubida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nombreImagen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        formatoActual = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        resolucion = new javax.swing.JTextField();
        formatoImagen = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        categoriaActual = new javax.swing.JTextField();
        categorias = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        guardarI = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Editar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Datos Imagen");

        LabelImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("<<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText(">>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        elminarImagen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        elminarImagen.setText("Eliminar");
        elminarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elminarImagenActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Descripción Imagen / Máximo 150 caracteres");

        descripcionImagen.setColumns(20);
        descripcionImagen.setRows(5);
        jScrollPane1.setViewportView(descripcionImagen);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Datos");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Fecha subida");

        fechaSubida.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nombre Imagen");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Formato Actual");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Resolución");

        formatoImagen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------------------", "JGP", "PNG" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Formato Imagen");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Categoría actual");

        categorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------------------" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Categorías");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        guardarI.setText("Guardar");
        guardarI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarIActionPerformed(evt);
            }
        });

        jButton6.setText("Regresar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarI, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(guardarI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(elminarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(57, 57, 57))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nombreImagen)
                                        .addGap(6, 6, 6)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(formatoImagen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(categoriaActual, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(resolucion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(categorias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(177, 177, 177))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fechaSubida, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(formatoActual)))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fechaSubida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formatoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(4, 4, 4)
                                .addComponent(nombreImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formatoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(categorias, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categoriaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(elminarImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1)
                .addGap(4, 4, 4))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (contador < (imagenesCuenta.size() - 1)) {

            contador = 1 + contador;
            categorias.setSelectedItem("----------------------");
            formatoImagen.setSelectedItem("-----------------------");
            //Se invocaría este método cada vez que se presione el botón >> con el cambio de contador
            //Para traer los datos de las imágenes correspondiente
            //a una cuenta. Claramente, cada invocación actualiza los datos
            MostrarImagenes();
            desactivarCampos();

        }//Fin if

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (contador > 0) {

            contador = contador - 1;
            categorias.setSelectedItem("----------------------");
            formatoImagen.setSelectedItem("-----------------------");
            //Se invocaría este método cada vez que se presione el botón << con el cambio de contador
            //Para traer los datos de las imágenes correspondiente
            //a una cuenta. Claramente, cada invocación actualiza los datos
            MostrarImagenes();
            desactivarCampos();

        }//Fin if

    }//GEN-LAST:event_jButton1ActionPerformed

    private void guardarIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarIActionPerformed

        ControlImagen CI2 = new ControlImagen();

        NombreImagen = nombreImagen.getText();
        FormatoActual = formatoImagen.getSelectedItem().toString();
        CategoriaActual = categorias.getSelectedItem().toString();
        Resolucion = resolucion.getText();
        DescripcionImagen = descripcionImagen.getText();

        if (CategoriaActual.equals("----------------------")) {

            CategoriaActual = categoriaActual.getText();

        }//Fin if

        if (FormatoActual.equals("-----------------------")) {

            FormatoActual = formatoActual.getText();

        }//Fin if

        //*************************************************************************************************************************
        //Se actualiza los valores de la imagen, siempre y cuando el usuario haya realizado una actualización desde la aplicación
        imagenesCuenta.get(contador).setDescripcionImagen(DescripcionImagen);
        imagenesCuenta.get(contador).setFormato_Imagen(FormatoActual);
        imagenesCuenta.get(contador).setNombreImagen(NombreImagen);
        imagenesCuenta.get(contador).setResolucion(Resolucion);

        Imagen imagenActualizar = imagenesCuenta.get(contador);
        String pkCategoria = "";

        for (int i = 0; i < categoriasImagenes.size(); i++) {

            if (categoriasImagenes.get(i).getNombreCategoria().equals(CategoriaActual)) {

                pkCategoria = categoriasImagenes.get(i).getCodigoCategoria();
                imagenesCuenta.get(contador).setCategoriaImagen(CategoriaActual);

            }//Fin if

        }//Fin for

        //*************************************************************************************************************************
        boolean t = CI2.ActualizarDatos(imagenesCuenta.get(contador).getIdImagen(), imagenActualizar, pkCategoria);

        if (t) {

            JOptionPane.showMessageDialog(null, "Datos actualizados.");

        } else {

            JOptionPane.showMessageDialog(null, "Datos no actualizados.");

        }//Fin if

    }//GEN-LAST:event_guardarIActionPerformed

    private void elminarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elminarImagenActionPerformed

        int Respuesta = JOptionPane.showConfirmDialog(null, "¿Desea eliminar la imagen?");

        if (Respuesta == 0) {

            ControlImagen CI3 = new ControlImagen();

            ControlComentarioImagen CcImagen = new ControlComentarioImagen();

            String IdContenido = imagenesCuenta.get(contador).getIdImagen();

            comentariosImagenes = CcImagen.TraerComentarios(IdContenido);

            EliminarComentariosVideos();

            boolean t = CI3.EliminarImagen(IdContenido);

            if (t) {

                JOptionPane.showMessageDialog(null, "Datos de la imagen eliminados");
                //Se elimina el objeto de la imagen que quedó en el linkedlist
                imagenesCuenta.remove(contador);
                LabelImagen.setIcon(null);
                fechaSubida.setText("");
                formatoActual.setText("");
                categoriaActual.setText("");
                resolucion.setText("");
                descripcionImagen.setText("");
                nombreImagen.setText("");

                if (comentariosImagenes.isEmpty() == false) {

                    comentariosImagenes.clear();

                }//Fin condición para limpiar el linkedList

            } else {

                JOptionPane.showMessageDialog(null, "Datos de la imagen no eliminados");

            }//Fin if

        }//Fin if principal

    }//GEN-LAST:event_elminarImagenActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        GUIprincipal3 = new Principal();
        GUIprincipal3.show();
        GUIprincipal3.setNombreUsuarioPrincipal(NombreUsuarioImagenes);
        this.dispose();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed

        activarCampos();

    }//GEN-LAST:event_EditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosImagen().setVisible(true);
            }
        });
    }

    //Método para mostrar las imagenes en la aplicación
    public void MostrarImagenes() {

        fechaSubida.setText(imagenesCuenta.get(contador).getFechaSubidaI());
        nombreImagen.setText(imagenesCuenta.get(contador).getNombreImagen());
        formatoActual.setText(imagenesCuenta.get(contador).getFormato_Imagen());
        resolucion.setText(imagenesCuenta.get(contador).getResolucion());
        categoriaActual.setText(imagenesCuenta.get(contador).getCategoriaImagen());

        descripcionImagen.setText(imagenesCuenta.get(contador).getDescripcionImagen());

        ImagenSubida = imagenesCuenta.get(contador).getImagenCuenta();

        //Se pasa la imagen que está en un arreglo de byte para convertirlo en un icono
        ImageIcon icon = new ImageIcon(ImagenSubida);

        //Después de que la imagen está convertida en icono entonces se procede a escalar el icono con el tamaño que conserva el label
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(LabelImagen.getWidth(), LabelImagen.getHeight(), Image.SCALE_DEFAULT));

        //Se coloca la imagen con el tamaño que tiene en el label
        LabelImagen.setIcon(icono);

    }//Fin método

    public void TraerCategorias() {

        //Se trae todas las categorías pertenecientes a la BD
        ControlCategoria CC2 = new ControlCategoria();

        categoriasImagenes = CC2.LeerCategorias();

        for (int i = 0; i < categoriasImagenes.size(); i++) {

            categorias.addItem(categoriasImagenes.get(i).getNombreCategoria());

        }//Fin for

    }//Fin método

    public void TraerImagenesCuenta() {

        ControlImagen CI = new ControlImagen();

        //Devuelve un linkelist donde se encuentra guardado todos los datos de las imagenes de la cuenta
        imagenesCuenta = CI.TraerImagenes(NombreUsuarioImagenes);

        if (imagenesCuenta.isEmpty() == false) {

            MostrarImagenes();

            elminarImagen.setEnabled(true);
            guardarI.setEnabled(true);
            elminarImagen.setEnabled(true);
            guardarI.setEnabled(true);

        } else {

            JOptionPane.showMessageDialog(null, "No has agregado contenido de imagen a tu cuenta." + "\n\nNota: puedes agregar imágenes presionando la pestaña" + "\n[Imagen] que se encuentra en la ventana principal.");
            elminarImagen.setEnabled(false);
            guardarI.setEnabled(false);

        }//Fin if

    }//Fin método

    public void activarCampos() {

        formatoImagen.setEnabled(true);
        categorias.setEnabled(true);
        nombreImagen.setEnabled(true);
        resolucion.setEnabled(true);
        descripcionImagen.setEnabled(true);
        guardarI.setEnabled(true);

    }//Fin método

    public void desactivarCampos() {

        formatoActual.setEnabled(false);
        formatoImagen.setEnabled(false);
        categorias.setEnabled(false);
        categoriaActual.setEnabled(false);
        nombreImagen.setEnabled(false);
        resolucion.setEnabled(false);
        descripcionImagen.setEnabled(false);
        guardarI.setEnabled(false);

    }//Fin método

    public void EliminarComentariosVideos() {

        ControlComentarioImagen cComentarioImagen = new ControlComentarioImagen();

        if (comentariosImagenes.isEmpty() == false) {

            for (int i = 0; i < comentariosImagenes.size(); i++) {

                cComentarioImagen.EliminarComentariosImagenesCuenta(comentariosImagenes.get(i).getIdComentario());

            }//Fin for

        }//Fin condición

    }//Fin método

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editar;
    private javax.swing.JLabel LabelImagen;
    private javax.swing.JTextField categoriaActual;
    private javax.swing.JComboBox<String> categorias;
    private javax.swing.JTextArea descripcionImagen;
    private javax.swing.JButton elminarImagen;
    private javax.swing.JTextField fechaSubida;
    private javax.swing.JTextField formatoActual;
    private javax.swing.JComboBox<String> formatoImagen;
    private javax.swing.JButton guardarI;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField nombreImagen;
    private javax.swing.JTextField resolucion;
    // End of variables declaration//GEN-END:variables
}
