/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlCuenta;
import Modelo.CuentaUsuario;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateo
 */
public class ModificarDatos extends javax.swing.JFrame {

    Principal GUIprincipal3;

    String nuevaContraseña;
    String repetirContraseña;
    String Nombre1;
    String Nombre2;
    String Apellido1;
    String Apellido2;
    String fechaNacimiento;
    String Genero;
    String Email;
    String FechaCreacion;

    String NombreUsuarioModificar;

    JFileChooser seleccionador;
    File archivo;
    FileInputStream entrada;

    //Se convierte la imagen en un arreglo de bytes
    byte[] ImagenPerfil;

    CuentaUsuario cuentaU;
    String ubicacion;

    /**
     * Creates new form ModigicarDatos
     */
    public ModificarDatos(String NombreUsuarioM) {
        initComponents();
        this.setLocationRelativeTo(this);
        NombreUsuarioModificar = NombreUsuarioM;

        nuevaContraseña = null;
        repetirContraseña = null;
        Nombre1 = null;
        Nombre2 = null;
        Apellido1 = null;
        Apellido2 = null;
        fechaNacimiento = null;
        Genero = null;
        Email = null;
        seleccionador = new JFileChooser();
        archivo = null;
        FechaCreacion = null;

        MostrarDatosModificar();

        guardarDcuenta.setEnabled(false);
        NuevaContraseña.setEnabled(false);
        RepetirContraseña.setEnabled(false);
        EditarNombre1.setEnabled(false);
        EditarNombre2.setEnabled(false);
        EditarApellido1.setEnabled(false);
        EditarApellido2.setEnabled(false);
        EditarFechaNacimiento.setEnabled(false);

        contraseñaActual.setEnabled(false);
        fechaNActural.setEnabled(false);
        generoActual.setEnabled(false);
        GeneroF.setEnabled(false);
        GeneroM.setEnabled(false);
        EditarEmail.setEnabled(false);
        cambiarFoto.setEnabled(false);
        eliminarFoto.setEnabled(false);

    }

    public ModificarDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GeneroEditar = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        NuevaContraseña = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        EditarApellido2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        EditarApellido1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EditarNombre2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        EditarNombre1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        EditarLabelFoto = new javax.swing.JLabel();
        cambiarFoto = new javax.swing.JButton();
        eliminarFoto = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        EditarEmail = new javax.swing.JTextField();
        EditarFechaNacimiento = new com.toedter.calendar.JDateChooser();
        LabelFN = new javax.swing.JLabel();
        generoActual = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        fechaNActural = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        GeneroM = new javax.swing.JRadioButton();
        GeneroF = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        guardarDcuenta = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        RepetirContraseña = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        contraseñaActual = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Editar cuenta");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Cambio de contraseña");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nueva contraseña*");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Repetir contraseña");

        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Debe tener máximo 20 caracteres");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Datos de la cuenta");

        jLabel10.setText("Segundo apellido*");

        jLabel9.setText("Primer apellido*");

        jLabel8.setText("Segundo nombre*");

        jLabel7.setText("Primer nombre*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditarNombre1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(EditarNombre2)
                    .addComponent(EditarApellido1)
                    .addComponent(EditarApellido2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditarNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditarNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditarApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditarApellido2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel11.setText("FechaNacimiento*");

        EditarLabelFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cambiarFoto.setText("Cambiar");
        cambiarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarFotoActionPerformed(evt);
            }
        });

        eliminarFoto.setText("Eliminar");
        eliminarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarFotoActionPerformed(evt);
            }
        });

        jLabel13.setText("Foto perfil*");

        jLabel15.setText("Correo cuenta*");

        LabelFN.setForeground(new java.awt.Color(153, 153, 153));
        LabelFN.setText("Observación:");

        jLabel16.setText("Genero actual");

        jLabel12.setText("Fecha Nacimiento Actual");

        GeneroEditar.add(GeneroM);
        GeneroM.setText("Masculino");

        GeneroEditar.add(GeneroF);
        GeneroF.setText("Femenino");

        jLabel27.setText("Genero*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(EditarLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cambiarFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminarFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(fechaNActural, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditarFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(EditarEmail)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelFN)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(GeneroF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GeneroM))
                            .addComponent(jLabel27))
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EditarLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cambiarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EditarFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(fechaNActural))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelFN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GeneroF)
                        .addComponent(GeneroM)))
                .addGap(8, 8, 8)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Botones"));
        jPanel3.setFocusTraversalPolicyProvider(true);

        guardarDcuenta.setText("Guardar");
        guardarDcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDcuentaActionPerformed(evt);
            }
        });

        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guardarDcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guardarDcuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(editar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Contraseña actual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(NuevaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RepetirContraseña)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(contraseñaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NuevaContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RepetirContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contraseñaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        GUIprincipal3 = new Principal();
        GUIprincipal3.show();
        //Se envía el PK de la cuenta a la ventana principal
        GUIprincipal3.setNombreUsuarioPrincipal(NombreUsuarioModificar);
        this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void guardarDcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDcuentaActionPerformed

        Date date = EditarFechaNacimiento.getDate();

        if (date != null) {

            long d = date.getTime();
            java.sql.Date fecha = new java.sql.Date(d);

            fechaNacimiento = String.valueOf(fecha).substring(2, 10);

        }//Fin if

        if (fechaNacimiento == null) {

            fechaNacimiento = fechaNActural.getText().substring(2, 10);

        }//Fin if

        nuevaContraseña = NuevaContraseña.getText();
        repetirContraseña = RepetirContraseña.getText();
        Nombre1 = EditarNombre1.getText();
        Nombre2 = EditarNombre2.getText();
        Apellido1 = EditarApellido1.getText();
        Apellido2 = EditarApellido2.getText();

        //Genero = EditarGenero.getSelectedItem().toString();
        Email = EditarEmail.getText();

        if (GeneroF.isSelected()) {

            Genero = "F";

        } else if (GeneroM.isSelected()) {

            Genero = "M";

        } else {

            Genero = generoActual.getText();

        }//Fin if principal

        if (!"".equals(nuevaContraseña) && !"".equals(repetirContraseña)) {

            if (nuevaContraseña.equals(repetirContraseña)) {

                boolean t = false;

                ControlCuenta c1 = new ControlCuenta();

                //*********************************************************************
                if (archivo == null) {

                    cuentaU = new CuentaUsuario(Nombre1, Nombre2, Apellido1, Apellido2, NombreUsuarioModificar, Genero, Email, nuevaContraseña, FechaCreacion, fechaNacimiento);

                    t = c1.ModificarDatosCuenta(cuentaU, NombreUsuarioModificar);

                } else {

                    cuentaU = new CuentaUsuario(Nombre1, Nombre2, Apellido1, Apellido2, NombreUsuarioModificar, Genero, Email, nuevaContraseña, FechaCreacion, fechaNacimiento, archivo.toString());

                    t = c1.ModificarDatosCuentaFoto(cuentaU, NombreUsuarioModificar);

                }//Fin if

                //*********************************************************************
                if (t) {

                    JOptionPane.showMessageDialog(null, "Datos modificados.");

                }//Fin if

            } else {

                JOptionPane.showMessageDialog(null, "Las contraseñas ingresadas no coinciden. Verificar por favor.", "Error", JOptionPane.ERROR_MESSAGE);

            }//Fin segundo if

        } else {

            boolean t = false;

            ControlCuenta c2 = new ControlCuenta();

            //*********************************************************************
            if (archivo == null) {

                cuentaU = new CuentaUsuario(Nombre1, Nombre2, Apellido1, Apellido2, NombreUsuarioModificar, Genero, Email, contraseñaActual.getText(), FechaCreacion, fechaNacimiento);

                t = c2.ModificarDatosCuenta(cuentaU, NombreUsuarioModificar);

            } else {

                cuentaU = new CuentaUsuario(Nombre1, Nombre2, Apellido1, Apellido2, NombreUsuarioModificar, Genero, Email, contraseñaActual.getText(), FechaCreacion, fechaNacimiento, archivo.toString());

                t = c2.ModificarDatosCuentaFoto(cuentaU, NombreUsuarioModificar);

            }//Fin if

            //*********************************************************************
            if (t) {

                JOptionPane.showMessageDialog(null, "Datos modificados.");

            }//Fin if

        }//Fin primer if

    }//GEN-LAST:event_guardarDcuentaActionPerformed

    private void cambiarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarFotoActionPerformed

        int Resultado = JOptionPane.showConfirmDialog(null, "¿Está seguro/a de cambiar la foto de perfil?");

        if (Resultado == 0) {

            if (seleccionador.showDialog(null, null) == JFileChooser.APPROVE_OPTION) {

                archivo = seleccionador.getSelectedFile();

                if (archivo.canRead()) {

                    //El endsWith especifica si la cadena que compone el archivo imagen termina en jpg o png para ser verificada.
                    if (archivo.getName().endsWith("jpg") || archivo.getName().endsWith("png")) {

                        ImageIcon icon = new ImageIcon(archivo.toString());

                        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(EditarLabelFoto.getWidth(), EditarLabelFoto.getHeight(), Image.SCALE_DEFAULT));

                        //Se coloca la imagen con el tamaño que tiene el labol
                        EditarLabelFoto.setIcon(icono);

                    } else {

                        JOptionPane.showMessageDialog(null, "El Formato de la imagen no aceptado. Se recomienda: jpg o png.", "Error", JOptionPane.ERROR_MESSAGE);

                    }//Fin if

                }//Fin segundo if

            }//Fin primer if

        }//Fin if verificación

    }//GEN-LAST:event_cambiarFotoActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
      
        ActivarCampos();

    }//GEN-LAST:event_editarActionPerformed

    private void eliminarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarFotoActionPerformed

        //Este método elimina la foto de perfil que conserva el usuario, generando que se coloque 
        //una foto de perfil predeterminada por el aplicativo
        int Respuesta = JOptionPane.showConfirmDialog(null, "¿Desea eliminar la foto de perfil?");

        if (Respuesta == 0) {

            EditarLabelFoto.setIcon(null);
            ImagenPredeterminada();
            File nuevoArchivo = new File(ubicacion);
            archivo = nuevoArchivo;

        }//Fin if

    }//GEN-LAST:event_eliminarFotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarDatos().setVisible(true);
            }
        });
    }

    private void MostrarDatosModificar() {

        ControlCuenta cCuenta = new ControlCuenta();

        CuentaUsuario cUsuario = cCuenta.LeerCuenta(NombreUsuarioModificar);

        //nombreUsuario2.setText(cUsuario.getNombreUsuario());
        EditarNombre1.setText(cUsuario.getNombre1c());
        EditarNombre2.setText(cUsuario.getNombre2c());
        EditarApellido1.setText(cUsuario.getApellido1c());
        EditarApellido2.setText(cUsuario.getApellido2c());
        EditarEmail.setText(cUsuario.getEmail());
        generoActual.setText(cUsuario.getGenero());
        fechaNActural.setText(cUsuario.getFecha_Nacimiento());
        contraseñaActual.setText(cUsuario.getContrasena());
        FechaCreacion = cUsuario.getFecha_Creacion();

        //**********************************************************************************************************************************
        ImagenPerfil = cUsuario.getFotoPerfil();

        //Se pasa la imagen que está en un arreglo de byte para convertirlo en un icono
        ImageIcon icon = new ImageIcon(ImagenPerfil);

        //Después de que la imagen está convertida en icono entonces se procede a escalar el icono con el tamaño que conserva el label
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(EditarLabelFoto.getWidth(), EditarLabelFoto.getHeight(), Image.SCALE_DEFAULT));

        //Se coloca la imagen con el tamaño que tiene en el label
        EditarLabelFoto.setIcon(icono);

    }//Fin método

    //Método que establece la imagen predeterminada en la foto de perfil
    public void ImagenPredeterminada() {

        String barra = File.separator;
        ubicacion = System.getProperty("user.dir") + barra + "src" + barra + "Imagenes" + barra + "Perfil.jpg" + barra;
        ImageIcon icon2 = new ImageIcon(ubicacion);
        Icon icono2 = new ImageIcon(icon2.getImage().getScaledInstance(EditarLabelFoto.getWidth(), EditarLabelFoto.getHeight(), Image.SCALE_DEFAULT));
        EditarLabelFoto.setIcon(icono2);

    }//Fin mñétodo

    public void ActivarCampos() {

        guardarDcuenta.setEnabled(true);
        NuevaContraseña.setEnabled(true);
        RepetirContraseña.setEnabled(true);
        EditarNombre1.setEnabled(true);
        EditarNombre2.setEnabled(true);
        EditarApellido1.setEnabled(true);
        EditarApellido2.setEnabled(true);
        EditarFechaNacimiento.setEnabled(true);

        GeneroF.setEnabled(true);
        GeneroM.setEnabled(true);
        EditarEmail.setEnabled(true);
        cambiarFoto.setEnabled(true);
        eliminarFoto.setEnabled(true);

    }//Fin método

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EditarApellido1;
    private javax.swing.JTextField EditarApellido2;
    private javax.swing.JTextField EditarEmail;
    private com.toedter.calendar.JDateChooser EditarFechaNacimiento;
    private javax.swing.JLabel EditarLabelFoto;
    private javax.swing.JTextField EditarNombre1;
    private javax.swing.JTextField EditarNombre2;
    private javax.swing.ButtonGroup GeneroEditar;
    private javax.swing.JRadioButton GeneroF;
    private javax.swing.JRadioButton GeneroM;
    private javax.swing.JLabel LabelFN;
    private javax.swing.JTextField NuevaContraseña;
    private javax.swing.JTextField RepetirContraseña;
    private javax.swing.JButton cambiarFoto;
    private javax.swing.JTextField contraseñaActual;
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminarFoto;
    private javax.swing.JTextField fechaNActural;
    private javax.swing.JTextField generoActual;
    private javax.swing.JButton guardarDcuenta;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
